import { copyFileSync, existsSync, mkdirSync } from "fs";
import { join } from "path";
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const outDir = "build";
const staticAssets = ["manifest.json", "styles.css"];

console.log(`Building in ${prod ? "production" : "development"} mode...`);
console.log(`Output directory: ${outDir}`);

const copyStaticAssets = () => {
	mkdirSync(outDir, { recursive: true });
	for (const asset of staticAssets) {
		if (existsSync(asset)) {
			copyFileSync(asset, join(outDir, asset));
		}
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: outDir,
	entryNames: "main",
	minify: prod,
	plugins: [{
		name: "copy-static-assets",
		setup: (build) => {
			build.onStart(() => {
				copyStaticAssets();
			});
		},
	}],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
